config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  #get 'home/index'
  get 'home/about'
  root 'home#index' #set as home page
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user

	def self.search(search)
		if search
			contact = Contact.find_by(fname: search)
			if Contact
				self.where(userId: Contact)
			else
				Contact.all
			end
		else
			Contact.all
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contact	#user can have many contacts - association
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.search (params[:search])
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contact.build
  end

  # GET /contacts/1/edit
  def edit
  end

  

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contact.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contact.find_by(id: params[:id]) #the correct user is the current user that has been associated with the userid
    redirect_to contacts_path, notice: "Not Authorised" if @contact.nil? #if not the correct user throw an error message
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:fname, :lname, :email, :phone, :instagram, :user_id, :search)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field form-group">
    <%= form.text_field :fname,
        class:"form-control",
        placeholder: "First Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :lname,
        class:"form-control",
        placeholder: "Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email,
        class:"form-control",
        placeholder: "Email Address" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone,
        class:"form-control",
        placeholder: "Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram,
        class:"form-control",
        placeholder: "instagram" %>
  </div>

  <div class="field form-group">
   <%= form.text_field :user_id,
       id: :contact_user_id,
       class:"form-control",
       value:  current_user.id,
       type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-info"%>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>
<br/>

<%= link_to 'Show', @contact,  class:"btn btn-info" %> 
<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>



<table class = "table table-striped table-hover">
      
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Instagram</th>
      <th>User Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>  
    <% @contacts.each do |contact| %>
    <% if contact.user == current_user %>
      <tr>
        <td><%= contact.fname %></td>
        <td><%= contact.lname %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.instagram %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= form_tag(contacts_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<br>

<%= link_to 'New Contact', new_contact_path, class:"btn btn-info" %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>
<br/>

<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>First name:</strong>
  <%= @contact.fname %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @contact.instagram %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact), class:"btn btn-info" %> 
<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
  <%= link_to 'Contacts', root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      	<%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>

   
      <% if user_signed_in? %>
      <li class="nav-item">
      	<%= link_to "Contacts", contacts_path, class:"nav-link" %>
      </li>

	  <li class="nav-item">
      	<%= link_to "New Contact", new_contact_path, class:"nav-link" %>
      </li>

      	<li class="nav-item">
      	<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>

      <li class="nav-item">
      	<%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>
     <% else %>
      <li class="nav-item">
      	<%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
      	<%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>

    <% end %>

      
    </ul>
    
  </div>
</nav>

app/views/home/about.html.erb
<div class="about-section">
  <h1>About Us Page</h1>
  <p>Web page is hosted on Heroku</p>
  <p>Ruby on Rails</p>
</div>

<h2 style="text-align:center">Cloud Application Development</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <div class="container">
        <h2>Alan Mellowes</h2>
        <p class="title"></p>
        <p>Project for cloud application development</p>
        <p>x18467362@student.ncirl.ie</p>
      </div>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<h1>Home page</h1>
<p>Information management system that manages your contacts for you</p>
<br></br>
<p>Keep track of your contacts, simple create a new contact and enter in their details</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Contacts</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>

    <div class = "container">
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>